name: PASRA Daily Govt Jobs Scraper

on:
  schedule:
    - cron: '30 2 * * *'   # Subah 8:00 AM IST (UTC 2:30 AM)
    - cron: '30 14 * * *'  # Shaam 8:00 PM IST (UTC 14:30)
  workflow_dispatch:       # Manual run button ke liye

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: python auto_scrape.py

    - name: Show logs
      run: cat scrape_log.txt || echo "No log file"
